modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "underground_rivers"
version = "1.0.0"
displayName = "Underground Rivers"
logoFile="pack.png"
authors = "Apollo"
description = '''Rivers, but underground! Wild, isn't it?'''


[[dependencies.underground_rivers]]
modId = "neoforge"
type="required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.underground_rivers]]
modId = "minecraft"
type="required"
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.underground_rivers]]
modId = "lithostitched"
type="required"
versionRange = "[1.3.1,)"
ordering = "NONE"
side = "BOTH"